// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Transaction struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Nonce                uint64   `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 *Data    `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	ChainId              uint32   `protobuf:"varint,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,9,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,10,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Alg                  uint32   `protobuf:"varint,11,opt,name=alg,proto3" json:"alg,omitempty"`
	Sign                 []byte   `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "corepb.Data")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xe5, 0x34, 0xfd, 0x93, 0xdb, 0x7c, 0x9f, 0xc0, 0x62, 0xb8, 0x08, 0x06, 0xab, 0x93,
	0xa7, 0x0e, 0xc0, 0x23, 0xb0, 0x20, 0x31, 0x20, 0x8b, 0xbd, 0xba, 0x4d, 0x4c, 0x62, 0x29, 0xb1,
	0xad, 0xd8, 0x20, 0xf5, 0x9d, 0x78, 0x48, 0x64, 0x87, 0xd2, 0xed, 0xfc, 0xce, 0xd1, 0xb9, 0xf2,
	0x31, 0x5c, 0xc7, 0x89, 0x6c, 0xa0, 0x26, 0x1a, 0x67, 0xf7, 0x7e, 0x72, 0xd1, 0xf1, 0x55, 0xe3,
	0x26, 0xed, 0x8f, 0xbb, 0x27, 0x28, 0x9f, 0x29, 0x12, 0xe7, 0x50, 0xc6, 0x93, 0xd7, 0xc8, 0x04,
	0x93, 0x95, 0xca, 0x9a, 0x23, 0xac, 0x3d, 0x9d, 0x06, 0x47, 0x2d, 0x16, 0x82, 0xc9, 0x5a, 0x9d,
	0x71, 0xf7, 0x5d, 0xc0, 0xf6, 0xfd, 0x72, 0x33, 0xb5, 0x7b, 0x0a, 0x7d, 0x6e, 0xd7, 0x2a, 0xeb,
	0xe4, 0x7d, 0x4c, 0x6e, 0xfc, 0xad, 0x66, 0xcd, 0xff, 0x43, 0x11, 0x1d, 0x2e, 0xb2, 0x53, 0x44,
	0xc7, 0x6f, 0x60, 0xf9, 0x45, 0xc3, 0xa7, 0xc6, 0x32, 0x5b, 0x33, 0x24, 0xd7, 0x3a, 0xdb, 0x68,
	0x5c, 0x0a, 0x26, 0x4b, 0x35, 0x03, 0xbf, 0x87, 0x2a, 0x9a, 0x51, 0x87, 0x48, 0xa3, 0xc7, 0x95,
	0x60, 0x72, 0xa1, 0x2e, 0x06, 0x17, 0x50, 0xb6, 0x14, 0x09, 0xd7, 0x82, 0xc9, 0xed, 0x43, 0xbd,
	0x9f, 0xe7, 0xed, 0xd3, 0x36, 0x95, 0x13, 0x7e, 0x0b, 0x9b, 0xa6, 0x27, 0x63, 0x0f, 0xa6, 0xc5,
	0x8d, 0x60, 0xf2, 0x9f, 0x5a, 0x67, 0x7e, 0x69, 0xf9, 0x1d, 0x54, 0x1d, 0x85, 0x83, 0x9f, 0x4c,
	0xa3, 0xb1, 0xca, 0x4f, 0xd9, 0x74, 0x14, 0xde, 0x12, 0x9f, 0xc3, 0xc1, 0x8c, 0x26, 0x22, 0xfc,
	0x85, 0xaf, 0x89, 0xf9, 0x15, 0x2c, 0x68, 0xe8, 0x70, 0x9b, 0xef, 0x25, 0x99, 0x66, 0x07, 0xd3,
	0x59, 0xac, 0xe7, 0xd9, 0x49, 0x1f, 0x57, 0xf9, 0xcf, 0x1f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x23, 0xda, 0x8c, 0xaa, 0x88, 0x01, 0x00, 0x00,
}
